### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by jot4p** [eSkiSo/codigo_at#1]
Olá, 

Julgo que o código não está a funcionar, retorna sempre "Could not connect to host":

`ERRO
SoapFault Object
(
    [message:protected] => Could not connect to host
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => C:\xampp\htdocs\codigoat\index.php
    [line:protected] => 229
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => C:\xampp\htdocs\codigoat\index.php
                    [line] => 229
                    [function] => __doRequest
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array 

............`

**Comment by eSkiSo** [comment]
É os certificados, tambem tentei e deu erro, tenta com estes (substitui a pasta certs e wsdl)
[certs_wsdl.zip](https://github.com/eSkiSo/codigo_at/files/8491405/certs_wsdl.zip)

**Comment by eSkiSo** [comment]
Related with certificates. Closed.
